src/apis/api-endpoint.ts, src/apis/server-env.ts, src/utils/assert.ts
=> feat: implement api endpoint

.github/workflows/deploy-vercel.yml, build.sh
=> chore: 개인 repo로 push하는 action 스크립트 추가

.github/workflows/pr-title-checker.yml
pr subject를 한국어로 입력 가능하도록 수정했습니다.
=> chore: 풀 리퀘스트 subject 한국어 허용

src/app/globals.css, src/app/not-found.tsx
=> feat: not found page

package-lock.json, package.json, src/app/(routes)/quiz/components/quiz-fireworks.tsx, src/app/(routes)/quiz/components/quiz.tsx
=> feat: 퀴즈 정답시 confetti animation를 표시한다

src/app/api/auth/[...nextauth]/auth.ts, src/middleware.ts
- getUser 요청을 로그인 시에만 실행하도록 수정
=> fix: modify next-auth jwt callback fn

src/apis/fetchers/auth/sign-in.ts, src/app/api/auth/[...nextauth]/auth.ts
=> feat: 서버 토큰 만료 시, session 제거

cspell.json, package-lock.json, package.json, src/apis/fetchers/auth/sign-in.ts, src/app/(routes)/(tabs)/main/components/achievements.tsx, src/app/(routes)/(tabs)/main/components/my-stars-drawer-dialog.tsx, src/app/(routes)/(tabs)/main/page.tsx, src/app/api/auth/[...nextauth]/auth.ts, src/components/page-title.tsx, src/components/ui/drawer.tsx, src/hooks/use-media-query.ts
https://github.com/picktoss/pick-toss-next/assets/88191233/ae2d1757-8625-4913-8c69-acd27e9316d8
=> feat: my stars drawer-dialog

src/apis/api-endpoint.ts, src/apis/fetchers/key-point/get-bookmarks.ts, src/apis/fetchers/key-point/toggle-bookmark.ts, src/app/(routes)/(tabs)/review/page.tsx, src/app/(routes)/(tabs)/review/picks/components/category-select.tsx, src/app/(routes)/(tabs)/review/picks/components/delete-dropdown.tsx, src/app/(routes)/(tabs)/review/picks/page.tsx, src/components/common-layout.tsx, src/components/tab-nav.tsx, src/components/ui/button.tsx
=> feat: bookmarks page

package-lock.json, package.json, src/apis/api-endpoint.ts, src/apis/fetchers/quiz/create-quizzes.ts, src/apis/fetchers/quiz/get-today-quiz-set-id.ts, src/app/(routes)/(tabs)/main/components/lotties.tsx, src/app/(routes)/(tabs)/main/components/make-quiz-drawer-dialog.tsx, src/app/(routes)/(tabs)/main/components/quiz-maker.tsx, src/app/(routes)/(tabs)/main/page.tsx, src/components/ui/button.tsx, src/components/ui/checkbox.tsx, src/hooks/use-check-list.ts, src/hooks/use-force-update.ts
=> feat: create quiz

src/apis/api-endpoint.ts, src/apis/fetchers/key-point/get-key-points.ts, src/apis/types/dto/document.dto.ts, src/app/(routes)/(document)/document/[documentId]/components/ai-pick.tsx
=> feat: ai pick polling

src/app/(routes)/(tabs)/review/picks/page.tsx, src/components/tab-nav.tsx
=> fix: saved pick, display category & document name

src/apis/server-env.ts
=> chore: prod api 경로 추가

src/app/email/email_verification.html
=> feat: email verification template

src/apis/api-endpoint.ts, src/apis/fetchers/quiz/get-example-quizzes/fetcher.ts, src/apis/fetchers/quiz/get-example-quizzes/query.ts, src/app/(routes)/(tabs)/main/components/quiz-banner.tsx, src/app/(routes)/(tabs)/review/components/quiz-analysis.tsx, src/app/(routes)/(tabs)/review/components/top-five.tsx, src/app/(routes)/quiz/practice/components/example-mix-up-options.tsx, src/app/(routes)/quiz/practice/components/example-multiple-options.tsx, src/app/(routes)/quiz/practice/components/example-question.tsx, src/app/(routes)/quiz/practice/components/example-quiz-header.tsx, src/app/(routes)/quiz/practice/components/example-quiz-intro.tsx, src/app/(routes)/quiz/practice/components/example-quiz-result.tsx, src/app/(routes)/quiz/practice/components/example-quiz.tsx, src/app/(routes)/quiz/practice/page.tsx, src/lib/api-client/api-client.ts, src/middleware.ts
=> feat: example quiz

src/app/(routes)/(landing)/components/header.tsx
=> refactor: 구독 및 결제 dialog 추가

.github/workflows/ci.yml, package-lock.json, package.json, src/app/layout.tsx, src/contexts/amplitude-context.tsx, src/hooks/use-amplitude-context.ts
=> chore: setup amplitude

src/app/(routes)/(tabs)/profile/components/suggest-tip.tsx, src/app/(routes)/(tabs)/profile/page.tsx, src/components/common-layout/components/desktop.tsx
=> feat: suggest registration email

src/apis/fetchers/document/create-ai-pick/mutation.ts, src/apis/fetchers/document/re-create-ai-pick/mutation.ts, src/app/(routes)/(document)/(detail)/document/[documentId]/ui/pick-accordion.tsx, src/app/(routes)/(document)/create/page.tsx, src/app/(routes)/(document)/modify/[documentId]/page.tsx, src/app/(routes)/(tabs)/main/components/continuous-quiz-drawer-dialog.tsx, src/app/(routes)/(tabs)/main/components/make-quiz-drawer-dialog.tsx, src/app/(routes)/(tabs)/main/components/my-stars-drawer-dialog.tsx, src/app/(routes)/(tabs)/main/components/quiz-banner.tsx, src/app/(routes)/(tabs)/repository/[categoryId]/components/document-list.tsx, src/app/(routes)/(tabs)/review/components/top-five.tsx, src/app/(routes)/(tabs)/review/components/ui/period-type-selector.tsx, src/app/(routes)/quiz/components/quiz.tsx, src/app/(routes)/quiz/practice/components/example-quiz.tsx, src/components/add-note-floating-button.tsx, src/components/ai-pick-dialog.tsx, src/components/amplitude/page-view-event.tsx, src/components/create-document-protector.tsx, src/components/left-sidebar.tsx, src/components/pro-dialog-trigger-wrapper.tsx, src/constants/document.ts, src/contexts/amplitude-context.tsx, src/hooks/use-amplitude-context.ts, src/utils/date.ts
=> feat: amplitude events

tailwind.config.ts
=> chore: set typography

src/app/v3/(routes)/(tabs)/main/page.tsx, src/shared/components/text.tsx
=> feat: text

package-lock.json, package.json, src/app/(routes)/(document)/(detail)/layout.tsx, src/app/(routes)/(tabs)/layout.tsx, src/app/v3/(routes)/(tabs)/collections/page.tsx, src/shared/components/bottom-navigation.tsx, src/shared/components/ui/tabs.tsx, src/shared/components/v3/category-tag.tsx, src/views/v3/collections/components/collection-list.tsx, src/views/v3/collections/components/collection.tsx, src/views/v3/collections/index.tsx, src/views/v3/collections/screens/exploration.tsx, src/views/v3/collections/screens/my-collection.tsx
=> feat: collection ui

src/app/(routes)/(tabs)/collections/page.tsx, src/app/layout.tsx, src/shared/components/bottom-navigation.tsx, src/shared/components/ui/drawer.tsx, src/views/collections/collections/components/exploration.tsx, src/views/collections/collections/components/my-collection.tsx, src/views/collections/collections/index.tsx, src/views/collections/components/collection.tsx, src/views/collections/components/start-quiz-drawer.tsx, src/views/quiz-note/components/header.tsx, src/views/quiz-note/components/note-list.tsx, tailwind.config.ts
=> feat: collection detail drawer

src/app/(routes)/collections/[id]/page.tsx, src/shared/components/fixed-bottom.tsx, src/views/collections/collection-detail/components/quiz-card/index.tsx, src/views/collections/collection-detail/index.tsx
=> feat: collection-detail

src/app/globals.css, src/views/note/create-note/editor/components/visual-editor.tsx, src/views/note/create-note/editor/index.tsx, src/views/note/create-note/editor/styles/remirror-custom.css, src/views/note/create-note/notion/index.tsx, src/views/note/create-note/ui/create-quiz-button.tsx, src/views/note/create-note/ui/folder-select-drawer.tsx, src/views/note/modify-note/components/visual-editor.tsx, src/views/note/modify-note/styles/remirror-custom.css, src/views/note/note-detail/components/add-collection-drawer.tsx, src/views/note/note-detail/components/header.tsx, src/views/note/note-detail/components/pick-drawer.tsx, src/views/note/note-detail/components/quiz-card-menu.tsx, src/views/note/note-detail/index.tsx, src/views/note/quiz-note/components/add-note-menu.tsx, src/views/note/quiz-note/components/animate-buttons.tsx, src/views/note/quiz-note/components/dimmed-background.tsx, src/views/note/quiz-note/components/folder-select-drawer.tsx, src/views/note/quiz-note/components/header.tsx, src/views/note/quiz-note/components/menu-dots-button.tsx, src/views/note/quiz-note/components/sort-icon-button.tsx, src/views/note/quiz-note/components/swipeable-note-card.tsx, src/views/shared/move-note-drawer.tsx, src/views/shared/new-quiz-drawer.tsx, src/views/shared/replay-quiz-drawer.tsx, tailwind.config.ts
- drawer max-w-mobile 적용
- 맞춰서 overlay 및 dropdown menu 위치 영역 안쪽으로 조정
- ui 변경에 따른 css 수정 (퀴즈노트 페이지 floating 버튼 색상 변경)
- visual editor css 수정
=> fix: 퀴즈노트 drawer width 조정 및 css 수정

src/views/profile/notification/components/notification-control-area/index.stories.tsx, src/views/profile/notification/index.stories.tsx, src/views/profile/profile-edit/components/set-name-dialog.tsx, src/views/profile/profile-edit/index.tsx
- 스토리북 수정
(fix 발견, 같이 진행했습니다)
- 프로필 수정 파트 cursor-pointer 수정
=> refactor: profile

package.json, src/app/(routes)/quiz/[id]/layout.tsx, src/app/(routes)/quiz/[id]/page.tsx, src/app/(routes)/quiz/layout.tsx, src/app/(routes)/quiz/page.tsx, src/features/email/components/verification/email-input/index.tsx, src/features/quiz/components/multiple-option/index.stories.ts, src/features/quiz/components/multiple-option/index.tsx, src/features/quiz/components/quiz-progress-bar/index.tsx, src/features/quiz/screen/bomb-quiz-view.tsx, src/features/quiz/screen/quiz-view.tsx, src/features/quiz/screen/random-quiz-view.tsx, src/shared/components/custom/icon/svg-components.tsx, src/shared/components/ui/progress.tsx, yarn.lock
[multiple-option storybook](https://6717b3d4841dc6ebfdf5edf2-joiywgpjeb.chromatic.com/?path=/docs/quiz-multipleoption--docs)
=> feat: quiz layout & multiple-option

src/features/quiz/components/ox-choice/index.stories.ts, src/features/quiz/components/ox-choice/index.tsx, src/features/quiz/screen/quiz-view.tsx
props에 따라 ox 상태를 조절하는 게 좀 복잡해보이네요
좀 더 좋은 방법(변수명이나 변수의 조합 등?)이 있다면 공유해주세요🥲
[storybook](https://6717b3d4841dc6ebfdf5edf2-pcqahzvfnf.chromatic.com/?path=/docs/quiz-oxchoice--docs)
=> feat: ox-quiz ui

src/features/quiz/components/quiz-explanation-drawer/index.stories.tsx, src/features/quiz/components/quiz-explanation-drawer/index.tsx, src/features/quiz/components/quiz-timer/index.stories.ts, src/features/quiz/components/quiz-timer/index.tsx, src/features/quiz/components/report-quiz-error-dialog/index.stories.tsx, src/features/quiz/components/report-quiz-error-dialog/index.tsx, src/features/quiz/config/index.tsx, src/features/quiz/screen/quiz-view.tsx, src/shared/components/custom/icon/svg-components.tsx, src/shared/components/ui/dialog.tsx, src/shared/hooks/use-timer.tsx
이 drawer는 shadcn으로 구현하기 애매해서 직접 만들었습니다..🥲
[drawer storybook](https://6717b3d4841dc6ebfdf5edf2-ssnttfivcw.chromatic.com/?path=/docs/quiz-quizexplanationdrawer--docs)
[timer storybook](https://6717b3d4841dc6ebfdf5edf2-ssnttfivcw.chromatic.com/?path=/docs/quiz-quiztimer--docs)
[ReportQuizErrorDialog](https://6717b3d4841dc6ebfdf5edf2-ssnttfivcw.chromatic.com/?path=/docs/quiz-resultquizerrordialog--docs)
=> feat: QuizView

src/app/(routes)/quiz/[id]/page.tsx, src/app/(routes)/quiz/page.tsx, src/features/quiz/screen/quiz-view.tsx, src/requests/quiz/index.tsx, src/shared/lib/axios/http.ts
fetch 로직에 대해서 전혀 추상화하지 않았습니다
굳이 급하게 추상화할 필요를 느끼지 못했고, 이후에 같이 어떻게 추상화하면 좋을지 의논해보고 싶었습니다
이번 PR에서는 fetch 관련 로직의 구조정도만 확인해주시면 될 것 같습니다!
=> feat: fetch-today-quiz

src/features/document/components/animate-buttons/index.tsx, src/features/document/config/index.tsx, src/features/document/constants/quiz-type.ts, src/features/document/screens/quiz.tsx, src/features/write/pages/write-document-page.tsx, src/shared/configs/constants.ts
- /editor => /write 변경에 맞춰 href 수정
- document 하위 constants를 config로 변경하고 정리
- 수정하는김에 글자수 제한 상수로 관리할 수 있도록 분리하고 변경된 css 적용
=> fix: 경로 editor를 write로 변경 + constants를 config로 변경

src/app/(routes)/document/(main)/@header/default.tsx, src/app/(routes)/document/(main)/page.tsx, src/features/pages/documents-in-directory.tsx, src/requests/document/hooks.ts, src/requests/document/index.tsx
=> refactor: fetch documents

src/app/(routes)/document/(create)/layout.tsx, src/features/directory/contexts/directory-context.tsx, src/features/document/components/directory-select-drawer/index.tsx, src/features/write/pages/write-document-page.tsx, src/requests/document/create-document.ts, src/types/document.d.ts
create layout에 DirectoryProvider 적용
select & create directory
create document
=> feat: create document

src/app/(routes)/collections/(main)/@header/default.tsx, src/features/collection/components/my-collection.tsx, src/features/directory/contexts/directory-context.tsx, yarn.lock
=> chore: link for create collection

src/app/(routes)/quiz/random/page.tsx, src/features/collection/components/collection.tsx, src/features/collection/components/create-collection-form.tsx, src/features/collection/components/exploration.tsx, src/features/collection/components/my-collection.tsx, src/features/collection/components/start-quiz-drawer.tsx, src/features/quiz/screen/random-quiz-view/index.tsx, src/requests/collection/hooks.ts, src/requests/collection/index.ts, src/shared/configs/endpoint.ts, src/shared/lib/axios/http.ts, src/types/collection.d.ts
=> feat: fetch collections

src/app/(routes)/payment/page.tsx
=> fix: v2 payment 연결

src/app/(routes)/document/[id]/(main)/@header/default.tsx, src/features/document/components/swipeable-document-card/index.tsx
- 문서 제목 스크롤 효과 + 문서 swipe 카드 제목 말줄임표 처리
=> feat: 문서 제목 스크롤 효과 + 문서 swipe 카드 제목 말줄임표 처리

src/app/(routes)/document/[id]/(main)/layout.tsx, src/features/quiz/components/bomb-animation-success/index.tsx, src/features/quiz/screen/intro-and-quiz-view.tsx, src/shared/components/custom/spring-up-card-animation.tsx
=> fix: quiz animation

src/app/(routes)/profile/account/page.tsx, src/app/api/auth/[...nextauth]/auth.ts, src/features/collection/components/detail-info/index.tsx, src/requests/auth/server.ts, src/requests/user/server.ts, src/shared/lib/axios/http-server.ts
=> fix: login issue

package-lock.json, package.json, src/features/collection/components/exploration.tsx, src/features/collection/components/select-category-drawer.tsx, src/features/collection/components/select-min-quiz-count-drawer.tsx, src/features/collection/components/select-quiz-type-drawer.tsx, src/features/collection/config/index.ts, src/requests/collection/client.ts, src/requests/collection/hooks.ts, src/shared/components/custom/fixed-bottom.tsx, src/shared/components/ui/radio-group.tsx, src/shared/configs/endpoint.ts
=> feat: sort collection

src/app/(routes)/collections/edit-info/[id]/@header/default.tsx, src/app/(routes)/collections/edit-info/[id]/layout.tsx, src/app/(routes)/collections/edit-info/[id]/page.tsx, src/features/collection/components/edit-collection-info-form.tsx, src/features/collection/components/my-collection-info-dropdown-menu.tsx, src/requests/collection/client.ts, src/requests/collection/hooks.ts
=> feat: edit collection info

src/app/(routes)/collections/edit-quiz/[id]/@header/default.tsx, src/app/(routes)/collections/edit-quiz/[id]/layout.tsx, src/app/(routes)/collections/edit-quiz/[id]/page.tsx, src/features/collection/components/create-collection-form.tsx, src/features/collection/components/edit-collection-quiz.tsx, src/features/collection/components/my-collection-info-dropdown-menu.tsx
=> feat: validate create collection

edit-collection-info-form.tsx, package-lock.json, package.json
=> feat: modify collection info validation

edit-collection-info-form.tsx, package-lock.json, package.json, src/features/collection/components/edit-collection-quiz.tsx, src/requests/collection/client.ts, src/requests/collection/hooks.ts
=> feat: modify collection quizzes

edit-collection-info-form.tsx, package-lock.json, package.json, src/app/(routes)/collections/(main)/@header/default.tsx, src/app/(routes)/collections/search/layout.tsx, src/app/(routes)/collections/search/page.tsx, src/features/collection/components/search-collection.tsx
=> feat: search collection wireframe

edit-collection-info-form.tsx, package-lock.json, package.json, src/app/(routes)/collections/(main)/@header/default.tsx, src/app/(routes)/collections/search/layout.tsx, src/app/(routes)/collections/search/page.tsx, src/features/collection/components/search-collection.tsx
=> feat: search collection ground work

edit-collection-info-form.tsx, src/app/(routes)/collections/create/@header/default.tsx, src/app/(routes)/collections/create/page.tsx, src/app/(routes)/collections/edit-quiz/[id]/@header/default.tsx, src/features/collection/components/create-collection-form.tsx, src/features/collection/components/edit-collection-info-form.tsx, src/features/collection/components/edit-collection-quiz.tsx, src/features/collection/components/edit-quiz-card.tsx, src/features/collection/components/exploration.tsx, src/features/collection/components/my-collection-info-dropdown-menu.tsx, src/features/collection/components/select-category-drawer.tsx
=> qa: collection

src/features/view/start-view.tsx
=> fix: start view debugging

src/features/view/start-view.tsx
=> fix: start view

src/features/view/splash.tsx, src/features/view/start-view.tsx
=> fix: splash

src/features/view/splash.tsx, src/features/view/start-view.tsx
=> fix: redirection time

src/features/view/splash.tsx, src/features/view/start-view.tsx
=> fix: redirection

src/app/(routes)/(landing)/page.tsx, src/features/view/splash.tsx, src/features/view/start-view.tsx
=> fix: start view splash and redirection

package-lock.json, src/app/api/auth/[...nextauth]/auth.ts, src/features/document/utils/index.tsx
=> fix: pdfjs cmap url
